// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5xAjr8TZwi392GGOzzjJqju8xNHqKwWE',
    appId: '1:110395103754:web:5b1fc0942f243c405d1df3',
    messagingSenderId: '110395103754',
    projectId: 'flutter-template-ac98b',
    authDomain: 'flutter-template-ac98b.firebaseapp.com',
    storageBucket: 'flutter-template-ac98b.firebasestorage.app',
    measurementId: 'G-KYFB3EHZTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOELHOnNsl7Qg8aT1SjFtT_0YchaMjp-E',
    appId: '1:110395103754:android:186e67564d5c64de5d1df3',
    messagingSenderId: '110395103754',
    projectId: 'flutter-template-ac98b',
    storageBucket: 'flutter-template-ac98b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnzY1Ky05F6WS8zGA0aslIPU1FZCAnc6I',
    appId: '1:110395103754:ios:f02be8c7e241d7565d1df3',
    messagingSenderId: '110395103754',
    projectId: 'flutter-template-ac98b',
    storageBucket: 'flutter-template-ac98b.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnzY1Ky05F6WS8zGA0aslIPU1FZCAnc6I',
    appId: '1:110395103754:ios:f02be8c7e241d7565d1df3',
    messagingSenderId: '110395103754',
    projectId: 'flutter-template-ac98b',
    storageBucket: 'flutter-template-ac98b.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5xAjr8TZwi392GGOzzjJqju8xNHqKwWE',
    appId: '1:110395103754:web:6fb65c26a897af325d1df3',
    messagingSenderId: '110395103754',
    projectId: 'flutter-template-ac98b',
    authDomain: 'flutter-template-ac98b.firebaseapp.com',
    storageBucket: 'flutter-template-ac98b.firebasestorage.app',
    measurementId: 'G-LXTG7DL3L4',
  );
}
